# <span style='background :green' > Web Scraping of iproperty Malaysia with BautifulSoup </span>

## Getting response from website

In [1]:
import requests
from bs4 import BeautifulSoup

headers={
    'accept': '*/*',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-GB,en;q=0.9',
    'cache-control': 'no-cache',
    'pragma': 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36'
}

## For sale houses data Extracting

In [134]:
# Initiating the list
price=[]
area=[]
address=[]
city_state=[]
details=[]
no_bedrooms=[]
no_bathrooms=[]
no_carpark=[]
agent=[]
contact=[]
post_date=[]

# extrating informations from all pages for Houses sale
for i in range(100):   # 100 pages 
  url= "https://www.iproperty.com.my/sale/all-residential/?page="+ str(i+1)
  response=requests.get(url,headers=headers)
  response_text=response.text.encode('utf-8')
  #rint(response)
  soup=BeautifulSoup(response_text,'lxml')
  #print(soup.title)
  listings=soup.find_all('div',attrs={'class':"PremiumCardstyle__CardWrapper-cvkMVX jRRXhG"})

  for listing in listings:
    if listing.find('li',attrs={'class':"ListingPricestyle__ItemWrapper-cBCBVa jXCKCc"}) is not None:
      pr=listing.find('li',attrs={'class':"ListingPricestyle__ItemWrapper-cBCBVa jXCKCc"}).text
    else:
      pr=listing.find('div',attrs={'class':"ListingPricestyle__RangePriceWrapper-lciGhp ftlHio"}).text
    
    if listing.find('div',attrs={'class':"ListingPricestyle__PricePSFWrapper-iaipCH ccOfpl listing-price-psf"}) is not None:
      dim=listing.find('div',attrs={'class':"ListingPricestyle__PricePSFWrapper-iaipCH ccOfpl listing-price-psf"}).text
    elif listing.find('div',attrs={'class':"PremiumCardstyle__HighlightWrapper-lfihyP fUHbyx"}) is not None:
      dim=listing.find('div',attrs={'class':"PremiumCardstyle__HighlightWrapper-lfihyP fUHbyx"}).text
    else:
      dim=listing.find('p',attrs={'class':"ListingAttributesstyle__ListingAttrsDescriptionItemWrapper-fQKuaA fJmpgN attributes-description-item"}).text
    
    if listing.find('h2',attrs={'class':"PremiumCardstyle__TitleWrapper-cBmVrL ePWFgo"}) is not None:
      add=listing.find('h2',attrs={'class':"PremiumCardstyle__TitleWrapper-cBmVrL ePWFgo"}).text
    else:
      add=listing.find('h2',attrs={'class':"PremiumCardstyle__TitleWrapper-cBmVrL lfKjpe"}).text
    
    city=listing.find('div',attrs={'class':"PremiumCardstyle__AddressWrapper-ldsjqp gRJjrp"}).text
    detail=listing.find('div',attrs={'class':"ListingAttributesstyle__ListingAttrsDescriptionWrapper-FnuGp ceWyz attributes-description"}).text.replace('\xa0','')
    
    if listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper bedroom-facility"}) is not None:
      bed=listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper bedroom-facility"}).text
    else:
      bed="NA"  

    if  listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper bathroom-facility"}) is not None:
      bath=listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper bathroom-facility"}).text
    else:
      bath="NA"

    if listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper carPark-facility"}) is not None:
      park=listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper carPark-facility"}).text
    else:
      park="NA"
   
    mobile=listing.find('a',attrs={'class':"phone-mobile"}).attrs['href']
    
    if listing.find('div',attrs={'class':"ListingHeadingstyle__HeadingTitle-bPnUeN cYvHoO"}) is not None:
      ag=listing.find('div',attrs={'class':"ListingHeadingstyle__HeadingTitle-bPnUeN cYvHoO"}).text
    elif listing.find('div',attrs={'class':"ListingHeadingstyle__HeadingTitle-bPnUeN iaUipM"}) is not None:
      ag=listing.find('div',attrs={'class':"ListingHeadingstyle__HeadingTitle-bPnUeN iaUipM"}).text
    else:
      ag="NA"
    
    if listing.find('p',attrs={'class':"ListingHeadingstyle__HeadingCreationDate-hVckGQ eUNCPm"}) is not None:
      post=listing.find('p',attrs={'class':"ListingHeadingstyle__HeadingCreationDate-hVckGQ eUNCPm"}).text
    elif listing.find('p',attrs={'class':"ListingHeadingstyle__HeadingCreationDate-hVckGQ gtCdOM"}) is not None:
      post=listing.find('p',attrs={'class':"ListingHeadingstyle__HeadingCreationDate-hVckGQ gtCdOM"}).text
    else:
      post="NA"
    
    price.append(pr)
    area.append(dim)
    address.append(add)
    city_state.append(city)
    details.append(detail)
    no_bedrooms.append(bed)
    no_bathrooms.append(bath)
    no_carpark.append(park)
    agent.append(ag)
    contact.append(mobile)
    post_date.append(post)

### Converting to dataframe from lists

In [135]:
import pandas as pd
header=['House Price','Size','Address', 'City, State','Details','Number of Bedrooms', 'Number of Bathrooms', 'Number of Carpark', 'Agent', 'Contact', 'post date']
indices=[i for i in range(1,len(price)+1)]
all_list=zip(price,area,address,city_state,details,no_bedrooms,no_bathrooms,no_carpark,agent,contact,post_date)
house_list=pd.DataFrame(list(all_list),columns=header,index=indices)
house_list

                         House Price  ...                       post date
1                       RM 3,600,000  ...           Posted today 07:52 AM
2                         RM 695,000  ...           Posted today 07:50 AM
3                         RM 180,000  ...           Posted today 07:48 AM
4     From RM 457,000 - RM 1,829,000  ...                              NA
5                         RM 299,000  ...           Posted today 07:48 AM
...                              ...  ...                             ...
2159                    RM 2,900,000  ...  Posted on 17 Sep 2021 07:02 AM
2160                      RM 455,000  ...  Posted on 17 Sep 2021 07:00 AM
2161                      RM 790,000  ...  Posted on 17 Sep 2021 06:59 AM
2162                      RM 959,000  ...  Posted on 17 Sep 2021 06:59 AM
2163                      RM 800,000  ...  Posted on 17 Sep 2021 06:58 AM

[2163 rows x 11 columns]

###Writing to csv file

In [136]:
# writing to csv
house_list.to_csv('iproperty_sale_houses.csv',index=False)

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Data Extrating (Houses for rent)

In [3]:
# Iniitating the list
price=[]
area=[]
address=[]
city_state=[]
details=[]
no_bedrooms=[]
no_bathrooms=[]
no_carpark=[]
agent=[]
contact=[]
post_date=[]

# Extracting data from all 100 pages
for i in range(100):
  url= "https://www.iproperty.com.my/rent/all-residential/?page="+ str(i+1)
  response=requests.get(url,headers=headers)
  response_text=response.text.encode('utf-8')
  
  soup=BeautifulSoup(response_text,'lxml')
  
  listings=soup.find_all('div',attrs={'class':"PremiumCardstyle__CardWrapper-cvkMVX jRRXhG"})

  for listing in listings:
    if listing.find('li',attrs={'class':"ListingPricestyle__ItemWrapper-cBCBVa jXCKCc"}) is not None:
      pr=listing.find('li',attrs={'class':"ListingPricestyle__ItemWrapper-cBCBVa jXCKCc"}).text
    else:
      pr=listing.find('div',attrs={'class':"ListingPricestyle__RangePriceWrapper-lciGhp ftlHio"}).text
    
    if listing.find('div',attrs={'class':"ListingPricestyle__PricePSFWrapper-iaipCH ccOfpl listing-price-psf"}) is not None:
      dim=listing.find('div',attrs={'class':"ListingPricestyle__PricePSFWrapper-iaipCH ccOfpl listing-price-psf"}).text
    elif listing.find('div',attrs={'class':"PremiumCardstyle__HighlightWrapper-lfihyP fUHbyx"}) is not None:
      dim=listing.find('div',attrs={'class':"PremiumCardstyle__HighlightWrapper-lfihyP fUHbyx"}).text
    else:
      dim=listing.find('p',attrs={'class':"ListingAttributesstyle__ListingAttrsDescriptionItemWrapper-fQKuaA fJmpgN attributes-description-item"}).text
    
    if listing.find('h2',attrs={'class':"PremiumCardstyle__TitleWrapper-cBmVrL ePWFgo"}) is not None:
      add=listing.find('h2',attrs={'class':"PremiumCardstyle__TitleWrapper-cBmVrL ePWFgo"}).text
    else:
      add=listing.find('h2',attrs={'class':"PremiumCardstyle__TitleWrapper-cBmVrL lfKjpe"}).text
    
    city=listing.find('div',attrs={'class':"PremiumCardstyle__AddressWrapper-ldsjqp gRJjrp"}).text
    detail=listing.find('div',attrs={'class':"ListingAttributesstyle__ListingAttrsDescriptionWrapper-FnuGp ceWyz attributes-description"}).text.replace('\xa0','')
    
    if listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper bedroom-facility"}) is not None:
      bed=listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper bedroom-facility"}).text
    else:
      bed="NA"  

    if  listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper bathroom-facility"}) is not None:
      bath=listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper bathroom-facility"}).text
    else:
      bath="NA"

    if listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper carPark-facility"}) is not None:
      park=listing.find('li',attrs={'class':"ListingAttributesstyle__ListingAttrsFacilitiesItemWrapper-jCPNCF eAeBYm attributes-facilities-item-wrapper carPark-facility"}).text
    else:
      park="NA"
   
    mobile=listing.find('a',attrs={'class':"phone-mobile"}).attrs['href']
    
    if listing.find('div',attrs={'class':"ListingHeadingstyle__HeadingTitle-bPnUeN cYvHoO"}) is not None:
      ag=listing.find('div',attrs={'class':"ListingHeadingstyle__HeadingTitle-bPnUeN cYvHoO"}).text
    elif listing.find('div',attrs={'class':"ListingHeadingstyle__HeadingTitle-bPnUeN iaUipM"}) is not None:
      ag=listing.find('div',attrs={'class':"ListingHeadingstyle__HeadingTitle-bPnUeN iaUipM"}).text
    else:
      ag="NA"
    
    if listing.find('p',attrs={'class':"ListingHeadingstyle__HeadingCreationDate-hVckGQ eUNCPm"}) is not None:
      post=listing.find('p',attrs={'class':"ListingHeadingstyle__HeadingCreationDate-hVckGQ eUNCPm"}).text
    elif listing.find('p',attrs={'class':"ListingHeadingstyle__HeadingCreationDate-hVckGQ gtCdOM"}) is not None:
      post=listing.find('p',attrs={'class':"ListingHeadingstyle__HeadingCreationDate-hVckGQ gtCdOM"}).text
    else:
      post="NA"
    
    price.append(pr)
    area.append(dim)
    address.append(add)
    city_state.append(city)
    details.append(detail)
    no_bedrooms.append(bed)
    no_bathrooms.append(bath)
    no_carpark.append(park)
    agent.append(ag)
    contact.append(mobile)
    post_date.append(post)

##Converting to Dataframe

In [4]:
import pandas as pd
header=['Rent Price','Size','Address', 'City, State','Details','Number of Bedrooms', 'Number of Bathrooms', 'Number of Carpark', 'Agent', 'Contact', 'post date']
indices=[i for i in range(1,len(price)+1)]
all_list=zip(price,area,address,city_state,details,no_bedrooms,no_bathrooms,no_carpark,agent,contact,post_date)
house_list=pd.DataFrame(list(all_list),columns=header,index=indices)
house_list

     Rent Price  ...                       post date
1      RM 8,500  ...           Posted today 10:17 AM
2        RM 950  ...           Posted today 10:15 AM
3      RM 2,000  ...           Posted today 10:08 AM
4      RM 2,500  ...           Posted today 10:08 AM
5      RM 3,800  ...           Posted today 10:01 AM
...         ...  ...                             ...
1996   RM 1,600  ...  Posted on 15 Sep 2021 01:57 AM
1997   RM 1,900  ...  Posted on 15 Sep 2021 01:53 AM
1998   RM 1,700  ...  Posted on 15 Sep 2021 01:46 AM
1999   RM 7,000  ...                              NA
2000   RM 1,000  ...  Posted on 15 Sep 2021 01:32 AM

[2000 rows x 11 columns]

## Wiritin into csv file

In [5]:
# writing to csv
house_list.to_csv('iproperty_rent_houses.csv',index=False)

## +++++++++++++++++++++++++++ The End ++++++++++++++++++++++++++++++++++++